package keyon.tang.po;

public class Dic extends DicKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic.weight
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer weight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.name
     *
     * @return the value of dic.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.name
     *
     * @param name the value for dic.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic.weight
     *
     * @return the value of dic.weight
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic.weight
     *
     * @param weight the value for dic.weight
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }
}