package keyon.tang.po;

public class SysAction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.url
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_action.method
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String method;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.id
     *
     * @return the value of sys_action.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.id
     *
     * @param id the value for sys_action.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.name
     *
     * @return the value of sys_action.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.name
     *
     * @param name the value for sys_action.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.url
     *
     * @return the value of sys_action.url
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.url
     *
     * @param url the value for sys_action.url
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.menu_id
     *
     * @return the value of sys_action.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.menu_id
     *
     * @param menuId the value for sys_action.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_action.method
     *
     * @return the value of sys_action.method
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_action.method
     *
     * @param method the value for sys_action.method
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }
}