package keyon.tang.po;

public class SysGroupMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_menu.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_menu.group_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group_menu.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_menu.id
     *
     * @return the value of sys_group_menu.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_menu.id
     *
     * @param id the value for sys_group_menu.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_menu.group_id
     *
     * @return the value of sys_group_menu.group_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_menu.group_id
     *
     * @param groupId the value for sys_group_menu.group_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group_menu.menu_id
     *
     * @return the value of sys_group_menu.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group_menu.menu_id
     *
     * @param menuId the value for sys_group_menu.menu_id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}