package keyon.tang.po;

public class SysGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_group.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.id
     *
     * @return the value of sys_group.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.id
     *
     * @param id the value for sys_group.id
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_group.name
     *
     * @return the value of sys_group.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_group.name
     *
     * @param name the value for sys_group.name
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}