package keyon.tang.po;

import java.util.Date;

public class SysParam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.param_key
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String paramKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.param_value
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private Date paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_param.param_desc
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    private String paramDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.param_key
     *
     * @return the value of sys_param.param_key
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.param_key
     *
     * @param paramKey the value for sys_param.param_key
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey == null ? null : paramKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.param_value
     *
     * @return the value of sys_param.param_value
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public Date getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.param_value
     *
     * @param paramValue the value for sys_param.param_value
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setParamValue(Date paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_param.param_desc
     *
     * @return the value of sys_param.param_desc
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public String getParamDesc() {
        return paramDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_param.param_desc
     *
     * @param paramDesc the value for sys_param.param_desc
     *
     * @mbg.generated Sun Apr 21 22:02:20 CST 2019
     */
    public void setParamDesc(String paramDesc) {
        this.paramDesc = paramDesc == null ? null : paramDesc.trim();
    }
}